### ISSUE TITLE
Unable to upload package to the channel quicklogic-corp from travis CI

### ISSUE THREAD

**Issue by kkumar23** [QuickLogic-Corp/ql_conda_eda#10]
I have set proper ANACONDA_USER and ANACONDA_TOKEN,  the travis shows green but the packages do not get uploaded to the channel .
Log for yosys:
Package Uploaded to ql label. /tmp/really-long-path/conda/conda-bld/linux-64/yosys-0.5_7872_g67948691-20200814_062958.tar.bz2
Using Anaconda API: https://api.anaconda.org
Using "[secure]" as upload username
Processing '/tmp/really-long-path/conda/conda-bld/linux-64/yosys-0.5_7872_g67948691-20200814_062958.tar.bz2'
Detecting file type...
File type is "conda"
Extracting conda package attributes for upload
Creating package "yosys"
Creating release "0.5_7872_g67948691"

**Comment by kowalewskijan** [comment]
Could you check token expiration date also?

**Comment by kkumar23** [comment]
I generated new and expiry is next year. I saw one option in the token which says special characters needs to be appended by “\”, I have added and will check.

**Comment by kkumar23** [comment]
The issue is fixed with the token special characters appended by “/”. Thanks for your help.

**Comment by kowalewskijan** [comment]
Great!
